package org.swgemu.core3.plugin.filters;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.StringWriter;
import java.util.Scanner;

import org.eclipse.core.internal.resources.File;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.jface.viewers.Viewer;
import org.eclipse.jface.viewers.ViewerFilter;

import org.eclipse.cdt.internal.core.model.TranslationUnit;

public class IdlGeneratedFilesFilter extends ViewerFilter {
	protected final String magic = "generated by engine3 IDL compiler";

	@Override
	public boolean select(Viewer arg0, Object arg1, Object arg2) {		
		if (arg2 instanceof TranslationUnit) {
			TranslationUnit unit = (TranslationUnit) arg2;

			if (unit.isCLanguage() || unit.isCXXLanguage()) {
				char test[] = unit.getContents();
				
				if (test != null) {
					String contents = String.copyValueOf(test, 0, Math.min(test.length, 0x100));

					if (contents.contains(magic)) {
						return false;
					}
				}
			}
		}
		
		return true;
	}

}
